language: ruby
gemfile: Gemfile.ci

before_install:
  - ./plugins/mezuro/script/install/install-rvm.sh
  - ./plugins/mezuro/script/install/kalibro.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "rvm reload"
  - "rvm use ruby-1.8.7-p302@mezuro"
  - "cp config/database.yml.sqlite3 config/database.yml"
  - "cp config/solr.yml.dist config/solr.yml"
  - "cp plugins/mezuro/service.yml.example plugins/mezuro/service.yml"
  - "cp plugins/mezuro/licenses.yml.example plugins/mezuro/licenses.yml"
  - "mkdir tmp"
  - "rake db:schema:load"
  - "rake db:migrate"
  - "rake makemo"
#  - "./script/sample-data"
  - "./script/noosfero-plugins enable mezuro"
  - "rake solr:download"
  - "rake db:test:prepare"
  - "rake test:noosfero_plugins:mezuro:units"
  - "rake test:noosfero_plugins:mezuro:functionals"
  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/configuration.feature"
  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/reading.feature"
  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/reading_group.feature"
  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/repository.feature"
  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/project.feature"
#  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/configuration.feature selenium"
#  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/reading.feature selenium"
#  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/reading_group.feature selenium"
#  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/repository.feature selenium"
#  - "DISPLAY=:99.0 ./plugins/mezuro/script/tests/run_acceptance_tests.sh plugins/mezuro/features/project.feature selenium"

notifications:
  email:
    - labxp2013-mezuro@googlegroups.com