language: ruby
gemfile: Gemfile.ci

before_install:
  ./plugins/mezuro/script/mezuro_rvm.sh
script:
  - "rvm reload"
  - "rvm use ruby-1.8.7-p302@mezuro"
  - "cp config/database.yml.sqlite3 config/database.yml"
  - "cp config/solr.yml.dist config/solr.yml"
  - "cp plugins/mezuro/service.yml.example plugins/mezuro/service.yml"
  - "cp plugins/mezuro/licenses.yml.example plugins/mezuro/licenses.yml"
  - "mkdir tmp"
  - "rake db:schema:load"
  - "rake db:migrate"
  - "rake makemo"
#  - "./script/sample-data"
  - "./script/noosfero-plugins enable mezuro"
  - "#Prepare Mezuro for running functional and unit tests"
  - "rake solr:download"
  - "rake db:test:prepare"
  - "rake test:noosfero_plugins:mezuro:units"
  - "rake test:noosfero_plugins:mezuro:functionals"

notifications:
  email:
    - labxp2013-mezuro@googlegroups.com 
