CREATE USER kalibro LOGIN ENCRYPTED PASSWORD 'kalibro' VALID UNTIL 'infinity';

CREATE DATABASE kalibro WITH ENCODING='UTF8'  OWNER=kalibro  CONNECTION LIMIT=-1;

CREATE DATABASE kalibro_teste WITH ENCODING='UTF8'  OWNER=kalibro  CONNECTION LIMIT=-1;

